import type { Metadata } from "next";

import Layout from "@/components/common/layout";
import { AppProps } from "next/app";
type AppOwnProps = { example: string };

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by allyes",
};
export const viewport = {
  maximumScale: 1, // Disable auto-zoom on mobile Safari
};

export default function MyApp({
  Component,
  pageProps,
}: AppProps & AppOwnProps) {
  return (
    <Layout>
      <Component {...pageProps} />
    </Layout>
  );
}
