import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { GNB } from "@/components/gnb";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by allyes",
};

export const viewport = {
  maximumScale: 1, // Disable auto-zoom on mobile Safari
};

const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <div className="w-full h-full flex flex-col grow">
        <GNB />
        <main className="flex w-full h-full flex-col">{children}</main>
      </div>
    </ThemeProvider>
  );
};

export default Layout;
